### ISSUE TITLE
Fix 1-click-bom extension integration

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#125]

**Comment by kasbah** [comment]
Port :3000 isn't allowed in Chrome for some reason so I had to upload a v1.7.5 version with just the `kitspace.test` domain (i.e. port 80). `kitspace.dev` is still enabled though and it's been released.

**Comment by AbdulrhmnGhanem** [comment]
I will add a `/1-click-BOM.tsv` route to the project page and make it redirect the actual asset URL. This will let us control the asset URL without modifying the extension, just change the redirect URL.

@kasbah, what do you think of this?

**Comment by kasbah** [comment]
ok

**Comment by kasbah** [comment]
I've added the `/1-click-BOM.tsv` route and fixed up the extension integration with #587. I've also updated 1clickBOM and pushed a new version to Google and Mozilla extension stores. Once #587 is merged in and new extensions are approved by the stores we can close this issue.
