### ISSUE TITLE
Sort out readme processing

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#128]
Right now it's done in Gitea but needs some post-processing to sort out the links. We should decide where we want to do the processing. Ideally we wouldn't have a cheerio dependency in the frontend.

https://github.com/kitspace/kitspace-v2/blob/e4e9ab98ed31d8bc61246ce5b69570dec681323c/frontend/src/utils/index.js#L37-L88

**Comment by AbdulrhmnGhanem** [comment]
Yes, I was going to propose moving this into the `processor`.
