### ISSUE TITLE
Error on staging: window.plausible is not a function

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#133]
Can be seen on https://master.staging.kitspace.dev/kaspar/ulx3s

```
TypeError: window.plausible is not a function
    NextJS 54
```

Strangely it's causing a "404" error, but also saying "An unexpected error occurred" rather than "Not found" or something more descriptive of a 404.

**Comment by kasbah** [comment]
I'm just updating the extension to include `kitspace.dev` so it's probably this one firing:

https://github.com/kitspace/kitspace-v2/blob/6da83c53f72aa9efb17606d83b02ebb804647b78/frontend/src/components/Board/BuyParts/index.js#L59-L65

Though, that shouldn't be calling plausible till someone actually clicks on a button?

**Comment by kasbah** [comment]
This was solved by #153, we should make sure it's not firing when just rendering the page though.

**Comment by AbdulrhmnGhanem** [comment]
> we should make sure it's not firing when just rendering the page though.

Can you elaborate please?

**Comment by kasbah** [comment]
If it was causing an error, just by loading the page, then somehow `window.plausible` was being invoked on load. We should doubly make sure these functions aren't being called when they shouldn't be.
