### ISSUE TITLE
Occasional failure to show sign up form confirmation message in cypress test

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#143]
- [CI](https://github.com/kitspace/kitspace-v2/runs/2878924958?check_suite_focus=true)
- [Cypress](https://dashboard.cypress.io/projects/d8hk55/runs/465/test-results/7d776cd1-e2d8-461b-8631-81437b7ea33f?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D)
- [Video](https://dashboard.cypress.io/projects/d8hk55/runs/465/test-results/7d776cd1-e2d8-461b-8631-81437b7ea33f/video)

**Comment by AbdulrhmnGhanem** [comment]
Closed via #183.
