### ISSUE TITLE
Staging server running out of space

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#158]
The deployment fails because there is no space left on the device. https://github.com/kitspace/kitspace-v2/runs/3092839149?check_suite_focus=true#step:10:444

**Comment by kasbah** [comment]
Well, log in and clear it out. :D

There should also be a cron job to remove docker images and volumes: https://github.com/kitspace/kitspace-v2/blob/master/ansible/roles/staging_server/tasks/docker.yml#L23

It might not be working correctly then...

**Comment by kasbah** [comment]
Hmm, seems like it's cleared out already.

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        39G  6.9G   32G  18% /
```

**Comment by AbdulrhmnGhanem** [comment]
> Well, log in and clear it out. :D

I did so.
But meant if there's something we can do about it to prevent this from happening again.

**Comment by kasbah** [comment]
Right, yeah, that's what that cron job is for. I guess it's not often enough. Maybe we need to clear it out as part of the deploy.

**Comment by kasbah** [comment]
I think https://github.com/kitspace/kitspace-v2/commit/da9720c9f7e1220ed96218c3ba32cc2ca5559e1b fixes this, feel free to re-open if it happens again.
