### ISSUE TITLE
Long response time when clicking project cards

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#160]
When clicking on a project on the main page in staging it takes a noticeable long time before anything happens. Even before the spinner shows (which we should get rid of for #131). Culprit seems to be the NextJS server serving up the required JSON. Probably this is due to too much happening in the `getServerSideProps`. 

![image](https://user-images.githubusercontent.com/206854/126071934-ba9e8955-f018-4abe-9238-7a91d441e669.png)

**Comment by AbdulrhmnGhanem** [comment]
Yes, I think we should only make two requests one to Gitea and one to the processor.

https://github.com/kitspace/kitspace-v2/pull/126#issuecomment-850997520

**Comment by kasbah** [comment]
While improving the processor API to be a single endpoint would help I'd like to see how far we can get with separate endpoints. They do have an advantage in that the front-end can decide what it wants to display and only request that. 

I think this response time can be improved by using `Promise.all` similar to what you did on the mulri page:

https://github.com/kitspace/kitspace-v2/blob/efe50fedec3d2537999ab843c21c947cc0b8f7ee/frontend/src/pages/[username]/[projectName]/[multiProjectName]/index.js#L36-L52

**Comment by kasbah** [comment]
Hmm, I guess what I looking at on abdo-dev.staging already was fetching all that concurrently. So it's not enough...

**Comment by AbdulrhmnGhanem** [comment]
I think we should profile it, instead of guessing which part is the bottleneck.

**Comment by AbdulrhmnGhanem** [comment]
Have you tried [clinicjs](https://clinicjs.org/) before?

**Comment by kasbah** [comment]
I've not come across it. Seems a bit overkill for this specific case maybe?

**Comment by AbdulrhmnGhanem** [comment]
I took a quick look. The CPU is mostly idle, most of the time is spent blocking on IO, probably the processor requests.
I will mock the processor requests and see if it solves the issue.

**Comment by kasbah** [comment]
Related to #185

**Comment by AbdulrhmnGhanem** [comment]
# Stats for ULX3S in the dev environment
* All requests to the processor resolve in `~250ms`.
![image](https://user-images.githubusercontent.com/37152329/132712152-39bed3ec-bdff-4dc2-96a0-19b94e613323.png)

##
I mocked the assets and gradually fetched the real assets, the summary below is the average of 4 samples.
| assets used| aggregate time for loading JSON|
|-----------------|------------------------|
|none| 100ms|
|`getKitspaceYAMLJson`| 183ms|
|`hasInteractiveBom` | 215ms|
| `getIsProcessingDone` | 232ms|
| `getBoardGerberInfo`| 252ms|
|`getBoardBomInfo` | 296ms|
| `getDefaultBranchFiles` | 755ms|

So the bottleneck is `getDefaultBranchFiles`, the files are needed for readme processing. I will finish #128 then test again.

**Comment by AbdulrhmnGhanem** [comment]
For ULX3S on the staging server, the response time in #202 is `250ms`-`300ms` when navigating by clicking on the card, and `400ms`-`600ms` when visiting the URL directly, previously it was `1200ms`.

**Comment by AbdulrhmnGhanem** [comment]
After activating caching (78f5c8412ca07c5cfccebf9b6f833726caf3b53f) in Nginx the improvement is negligible.
It gets "HIT" for all the processor assets though there's no reduction in the total loading time of the page, so I guess it's no longer the bottleneck.

**Comment by kasbah** [comment]
Surely Nginx is will cache on the first request though, so the first request is still slow.

**Comment by AbdulrhmnGhanem** [comment]
These stats are without caching, I haven't merged the caching yet.

**Comment by kasbah** [comment]
Alright but you said "After activating caching (...) there's no reduction in the total loading time of the page", so I meant: it being cached on the first request can explain that. Maybe it's still worth activating the caching.

**Comment by AbdulrhmnGhanem** [comment]
Sorry for the confusion!

**Comment by kasbah** [comment]
Seems to have improved, I'll open new issues if I notice any performance problems.
