### ISSUE TITLE
Auth checking and redirect needs to be done on next pages level

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#190]
as discussed on call

**Comment by AbdulrhmnGhanem** [comment]
I will start working on this though I am afraid we may hit something like #129.

**Comment by kasbah** [comment]
I never fully understood why you were hitting that problem in #129. To me it just shouldn't happen. I suggest taking your time to properly understand why the state is getting out of sync between server and client and make sure you are following NextJS best practices.
