### ISSUE TITLE
The `processor` deals with repo names case-insensitively 

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#235]
While working on #234, I noticed that the `processor` deals with repo names case-insensitively, I am not sure whether this will cause a problem in the future.

**Comment by kasbah** [comment]
The behavior is noted [in the docs](https://github.com/kitspace/kitspace-v2/tree/master/processor#parameters and is inherited from Gitea. The actual folders used by Gitea are all lower-case so we lower case inputs in the processor API.

https://github.com/kitspace/kitspace-v2/blob/8fd59348b692c5e21dfba77e481f2143e0bf44e0/processor/src/projectAPI.js#L77-L83

I think it's working fine. I don't think there are any bugs related to this at the moment so I am closing this. Feel free to re-open if you notice any issues of course.
