### ISSUE TITLE
WTF is the query parameter 1?

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#277]
Why is it there and why is it being removed?

https://github.com/kitspace/kitspace-v2/blob/45a7713c7a3da61500df52e3e6e79be27e724499/frontend/src/pages/login/index.js#L31-L36

**Comment by kasbah** [comment]
Oh it's the tab? Why not just `setOpenPane`? Why is it being pushed to the router at all? Either way it needs better naming.

**Comment by AbdulrhmnGhanem** [comment]
This bug was caused by https://github.com/kitspace/kitspace-v2/pull/240 simply setting the `openPane` didn't work.
