### ISSUE TITLE
Firefox visual testing is flaky due to viewport

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#294]
https://github.com/cypress-io/cypress/issues/15481

**Comment by AbdulrhmnGhanem** [comment]
Disabling it for now 2626364.

**Comment by kasbah** [comment]
https://github.com/kitspace/kitspace-v2/pull/268/commits/e0bc7a04531cb65f4289033638b3388d40bfd4e8

**Comment by AbdulrhmnGhanem** [comment]
This issue is irrelevant after #321
