### ISSUE TITLE
Import all current kitspace.org projects

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#338]

**Comment by AbdulrhmnGhanem** [comment]
## List of the imported project so far:
- [github.com / GenericLab](https://github.com/GenericLab/Unagi_Gar-Lampli)
- [github.com / less-smog](https://github.com/less-smog/hardware) (#346)
- [github.com / sgmk](https://github.com/sgmk/solarbird_shenzen_rdy) (#346, #347)

**Comment by kasbah** [comment]
I think that's enough importing for now I think. Lets' start fixing these. I'm working on readme things and I've self-assigned the ones I've spotted.

**Comment by AbdulrhmnGhanem** [comment]
All projects have been imported and all related issues have been addressed :tada:
