### ISSUE TITLE
Figure out how to build containers for staging/production

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#34]
Would be good to get make a Github action that builds the containers we use for staging and later production. We can probably push the containers to the Github registry? https://github.blog/2020-09-01-introducing-github-container-registry/

**Comment by AbdulrhmnGhanem** [comment]
Closed by https://github.com/kitspace/gitea/pull/9 & #41

**Comment by kasbah** [comment]
I think this issue should stay open till we start building containers for `the frontend and the new asset processor.
