### ISSUE TITLE
Should disable `Assembly Guide` for `solarbird_shenzen_rdy` and others

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#347]
|v1|v2
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/169001619-39f6ab30-6efd-4d0c-a3d6-a2b637c41c5c.png)|![image](https://user-images.githubusercontent.com/37152329/169001719-3a705f21-59a1-4112-90a5-1be70aa7940e.png)|

**Comment by kasbah** [comment]
On v1 we are keeping a list of projects where we omit the assmebly guide: https://github.com/kitspace/kitspace/blob/master/omit-ibom-boards.txt. I don't think we want to keep doing that, instead we'll have to get the projects to add a field in the kitspace.yaml to omit it.
