### ISSUE TITLE
`fast-response-diode` readme text style

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#350]
https://github.com/amchagas/fast-response-diode

|v1|v1|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/169028735-437331ef-eadc-49d2-ab5e-3524c050de2c.png)|![image](https://user-images.githubusercontent.com/37152329/169028791-7e48b1dd-1b15-4c7f-819d-1bbe7fd82d6d.png)|

**Comment by AbdulrhmnGhanem** [comment]
This is also an upstream issue but I am not sure if I can call it a bug; the link is empty
```markdown
This board and components can be ordered easily at [kitspace]()
```
clocking it in the Github repo redirects to a 404 page

**Comment by kasbah** [comment]
https://github.com/amchagas/fast-response-diode/pull/1
