### ISSUE TITLE
Why does cypress badge always say "failed"?

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#355]
![image](https://user-images.githubusercontent.com/206854/169668895-a66c1c0b-4476-40a8-8d23-3dcb8d5b6659.png)

And why does it say "No commit message available" all over the dashboard when you click on it? 

![image](https://user-images.githubusercontent.com/206854/169668910-8719445d-ccf6-41ae-9a20-e3c4ba5e5df6.png)

**Comment by AbdulrhmnGhanem** [comment]
Fixed the badge in fcf6c8c.
