### ISSUE TITLE
`mcu-cs` shouldn't have a readme

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#361]
In [v1](https://kitspace.org/boards/github.com/eez-open/modular-psu/mcu-cs/) the project doesn't have a readme.
|v1|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/169905883-7657ab0f-978b-4919-9496-eb7dd02e1962.png)|![image](https://user-images.githubusercontent.com/37152329/169905935-44a6644c-00d2-4eda-8bf8-ca25e2062fad.png)|

**Comment by kasbah** [comment]
I think picking up the root default README is fine. IIRC I wanted to do that on v1 but was stopped by my own convoluted code.
