### ISSUE TITLE
`nunchuk_breakout` wrong board showcase

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#371]
https://kitspace.org/boards/github.com/jana-marie/hoverboard-breakout/nunchuk_breakout/

|v1|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/170688191-9a37f77d-d8a3-46e6-a282-5e6afc108036.png)|![image](https://user-images.githubusercontent.com/37152329/170688252-6678d04c-0efe-4e9d-9f12-1515abd018c3.png)|

Though the IBOM is correct!
|v1|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/170688841-714da012-7acd-45b9-8239-c6f15ae85574.png)|![image](https://user-images.githubusercontent.com/37152329/170688657-b4b3b46a-71e3-43e3-8cc0-b18c00e93585.png)|

**Comment by AbdulrhmnGhanem** [comment]
Both command
https://github.com/kitspace/kitspace-v2/blob/98af50fdd5b201fb368affd5c7f7c70edac32b62/processor/src/tasks/processKicadPCB/index.ts#L70
and 
https://github.com/kitspace/kitspace-v2/blob/98af50fdd5b201fb368affd5c7f7c70edac32b62/processor/src/tasks/processKicadPCB/index.ts#L79
fail, but the error is returned in `stderr` so move this error into node we have to use something like
```js
if (stderr) {
  throw new Error(stderr)
}
```
But this doesn't explain why the ibom is right while the kicad file is corrupt.

**Comment by AbdulrhmnGhanem** [comment]
Actually, they fail for other boards too! It's an assertion not error
```
 failed to plot kicad gerbers
failed tester/ch330_hardware/059d467302fa712f2a8359c999bac46539a83ed7/images/layout.svg ../src/common/stdpbase.cpp(62): assert "traits" failed in Get(): create wxApp before calling this
../src/common/stdpbase.cpp(62): assert "traits" failed in Get(): create wxApp before calling this
../src/common/stdpbase.cpp(62): assert "traits" failed in Get(): create wxApp before calling this
```
Now I am not sure this is the root cause of this issue.

**Comment by kasbah** [comment]
stdpbase.cpp is used by Kicad  It fails on these .kicad_pcb because they were last saved with a nightly build of Kicad.

**Comment by kasbah** [comment]
It's using the folder provided in kitspace.yaml so it's not doing anything wrong as far as I can tell.

https://github.com/Jana-Marie/hoverboard-breakout/pull/11
