### ISSUE TITLE
`ArduTouch` and others missing project description

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#374]
|v1|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/170696356-51f08e4d-a2ee-4403-a586-1d1f381ddadc.png)|![image](https://user-images.githubusercontent.com/37152329/170696405-2b2c44d5-73eb-4759-aa21-1448c417811a.png)|

**Comment by kasbah** [comment]
This is down to not support a feature of kitspace-v1 yet: retrieving the description from a Github repo through the Github API.

**Comment by AbdulrhmnGhanem** [comment]
Actually, we fall back to the Gitea repo description but somehow it doesn't get imported!

![image](https://user-images.githubusercontent.com/37152329/170837996-866633a0-e1f2-4637-80de-15d8b38e52bd.png)

**Comment by kasbah** [comment]
Probably because we do a "Git" migration not a "Github" migration. Do we never want to migrate issues and wiki etc.

**Comment by AbdulrhmnGhanem** [comment]
> Probably because we do a "Git" migration not a "Github" migration

You are right!
