### ISSUE TITLE
e2e failing on master

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#405]
https://github.com/kitspace/kitspace-v2/runs/8033837709?check_suite_focus=true#step:9:1536

**Comment by AbdulrhmnGhanem** [comment]
The processor is flaky with the open-visual-simulator (#392)

![image](https://user-images.githubusercontent.com/37152329/186934341-955e1f78-c743-400c-9e69-9a6ea1d0e43f.png)

**Comment by AbdulrhmnGhanem** [comment]
No longer relevant.
