### ISSUE TITLE
Development setup is broken with the new docker setup

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#42]
When running `docker-compose build` it throws this error 
`ERROR: Forbidden path outside the build context: ../Dockerfile.gitea.dev ()`.
This happens on the `import-projects` branch.

**Comment by kasbah** [comment]
Hmm, strange, this works for me. What's your version of docker? Mine is:
```
$ docker -v
Docker version 19.03.13-ce, build 4484c46d9d
$ docker-compose -v
docker-compose version 1.27.4, build unknown
```
