### ISSUE TITLE
Add bottom borders for h2 tag in readme

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#422]
|Github|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/192760732-5f7e5441-37d3-43d6-8813-3da857d07b45.png)|![image](https://user-images.githubusercontent.com/37152329/192760909-3f197984-24b0-4c11-bdc2-25219cb8065f.png)|

**Comment by kasbah** [comment]
That's just a style thing? We don't need to completely copy Github's style...

**Comment by AbdulrhmnGhanem** [comment]
> That's just a style thing?

yes
