### ISSUE TITLE
`pslab-hardware` is totally inconsistent with v1

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#425]
https://github.com/fossasia/pslab-hardware

**Note: the project doesn't have a `kitspace.yaml` file.**

|v1|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/192766947-f7d89ebf-a254-49a1-82ff-189eb17a1742.png)|![image](https://user-images.githubusercontent.com/37152329/192766772-ec011d63-6340-4fa7-97ef-2ccd24ea1010.png)|
|![image](https://user-images.githubusercontent.com/37152329/192767274-2f1d1ab7-9c0c-4388-a726-39de167ea47f.png)|![image](https://user-images.githubusercontent.com/37152329/192766891-149462c3-8a04-40db-a2ed-07a5d446dadb.png)|
|![image](https://user-images.githubusercontent.com/37152329/192767132-1acd9cc8-2fdf-4996-962d-dfa979d323e9.png)|![image](https://user-images.githubusercontent.com/37152329/192767023-09fc0aef-aa9d-4386-9bd4-60158e4b965d.png)|

**Comment by kasbah** [comment]
Be aware that we lock down some projects to working versions:

https://github.com/kitspace/kitspace/blob/master/registry.json

**Comment by kasbah** [comment]
To be clear: we don't need to support locking down for alpha-2.
