### ISSUE TITLE
Use s3 for assets created by processor

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#462]
Just dropping some notes here for now. 

- Could use a [Minio](https://min.io/docs/minio/container/index.html) container for dev and use actual s3 or Cloudflare R2 or some other compatible service in production. 
- Mounting as a file-system could save some developer time but is a leaky abstraction and has performance implications. 
    - https://serverfault.com/questions/396100/s3fs-performance-improvements-or-alternative
    - https://hub.docker.com/r/efrecon/s3fs
    - https://github.com/cloudposse/goofys

**Comment by AbdulrhmnGhanem** [comment]
Closed via #494 and #512.
