### ISSUE TITLE
Script for migrating projects from kitspace.org

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#473]
What could be a good workflow for migrating everything to alpha-2 kitspace-v2? Maybe a script that does something like: 

- Get https://raw.githubusercontent.com/kitspace/kitspace/master/boards.txt
- Create all the users required
- Add all the repos required
- Makes sure redirects exist for:
    - `/boards/*/user/project/*` to `/user/project/*`
    -  `/interactive_bom/?*/user/project` to `/user/project/IBOM` 
    - `/interactive_bom/?*/user/project/sub` to `/user/project/sub/IBOM` 
    - maybe we just add a permanent wildcard redirects in nginx? 
    - we will have to make sure with and without trailing slashes re-directs

**Comment by AbdulrhmnGhanem** [comment]
- The username is the username in the git service
- The `*` in the first URL is the git service.
- The `?` in the IBOM URL is for query params not `optional.
