### ISSUE TITLE
Hiding unused functionality in frontend

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#476]
We need to:

- [x] hide sign-up / sign-in
- [x] hide `/projects/new` make add-a-project button link to `v1.kitspace.org/submit`
- [x] change `/newsletter` link to v1 or port it to v2

I'm leaning towards a strategy of deleting unused code and finding it in git history when we want to restore it. What do you think @AbdulrhmnGhanem ?

**Comment by AbdulrhmnGhanem** [comment]
Does `/newsletter/post` get proxied to a netlify function? If so how should this be handled in v2?
I think a redirect rule in the nextjs middleware would be sufficient.

**Comment by AbdulrhmnGhanem** [comment]
Completed via #501, #560, #561, #563, #566
