### ISSUE TITLE
`uncaught exception NS_ERROR_UNEXPECTED`  in Firefox e2e tests

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#508]
This happened several times in the logs and cypress throws so some tests fail.

https://github.com/kitspace/kitspace-v2/actions/runs/3542037302/jobs/5947470345#step:9:3628

**Comment by kasbah** [comment]
But the test you link is actually passing?

**Comment by AbdulrhmnGhanem** [comment]
Yes, because cypress re-runs a test if it fails. But sometimes this error gets thrown in the retries too.

https://github.com/kitspace/kitspace-v2/actions/runs/3542037302/jobs/5947109773#step:9:2793
