### ISSUE TITLE
`BeeHive` gerbers paths are inconsistent

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#533]
https://github.com/BeeHive-org/BeeHive
##

The `gerbers` paths for some projects needs updating. I already fixed it in https://github.com/kitspace-test-repos/BeeHive/commit/c5f2b61602532185ba15182d58e4f05b966f36eb. We will need to get this merged upstream.

**Comment by kasbah** [comment]
Make the PR please.

**Comment by AbdulrhmnGhanem** [comment]
https://github.com/BeeHive-org/BeeHive/pull/52
