### ISSUE TITLE
`dropbot-120-channel-pogo-pin-board.kicad` preview images are aligned to sides ()

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#541]
The top image is aligned to the left, and the bottom image to the right, they should be centered instead.
This is broken in v1 too.

![image](https://user-images.githubusercontent.com/37152329/210647477-a8d081bc-c098-4c8b-9e97-d33c24c53698.png)

**Comment by kasbah** [comment]
There is something (invisible) in the gerber or kicad file off to the right. I don't think there's anything sensible we can do about this on Kitspace.
