### ISSUE TITLE
Gitea frontend is broken

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#60]
After using the new dockerfile configuration on the #57 branch, the frontend is broken(CSS files aren't found) when reverted back it worked fine

**Comment by kasbah** [comment]
By dockerfile you mean `docker-compose.yml`, specifically the /etc/hosts mounting?

**Comment by AbdulrhmnGhanem** [comment]
Yes, the compose file, but I rolled back using using the dev version of
gitea to using the original file, not the /etc/hosts

**Comment by kasbah** [comment]
What does one have to do with the other?


On January 5, 2021 at 6:01 PM, Ghanem (notifications@github.com) wrote:
Yes, the compose file, but I rolled back using using the dev version of
gitea to using the original file, not the /etc/hosts

**Comment by AbdulrhmnGhanem** [comment]
See https://github.com/kitspace/kitspace-v2/pull/57/commits/2292429e061c29938d7a4a982e58ce50e011e3fe, the commenting those to lines fixed the Gitea frontend

**Comment by AbdulrhmnGhanem** [comment]
@kasbah, try running `docker images prune -a` not `system prune`. This may reproduce the error for you.

**Comment by AbdulrhmnGhanem** [comment]
Using `make build` instead of `make backend` in the command fixes the issue. The first time the container runs it will generate the assets. For subsequent builds, this step won't run `bindata for public already up-to-data`.

**Comment by AbdulrhmnGhanem** [comment]
Closed by 14eb006, and https://github.com/kitspace/gitea/commit/b122f52663c4f575e4d228df1c8b901e1395b1b3
