### ISSUE TITLE
Routes are a bit ugly right now

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#69]
I'm not a big fan of the `/projects/mine` route and some of the other ones. @AbdulrhmnGhanem I remember you saying you aren't too fond of it either. Let's come up with something better. Here's a start:

- route: `/` 
Proxy to to `/search` but still appears as `/`. When someone enters a search it will change to `/search?q=`. 
- route: `/search`
Display all projects, from most recently updated. You can add a search query as a parameter: `/search?q=` 
- route  `/<user-name>`
Proxy to `/search?q=user:user-name` (or however it actually works in Gitea search). Still appears as `/<user-name>`.
- route `/<user-name>/<project-name>`. 
Proxy to `/projects/<user-name>/<project-name>` but appears as `/<user-name>/<project-name>`
- route `/projects/<user-name>/<project-name>`
The project page.

**Comment by AbdulrhmnGhanem** [comment]
> * route `/projects/<user-name>/<project-name>`
>   The project page

I think a better option would be `<user-name>/<project-name>` just like GitHub and Gitea. I am OK with the rest.

**Comment by kasbah** [comment]
Agreed, that's why we have: 

> route `/<user-name>/<project-name>`.
> Proxy to `/projects/<user-name>/<project-name>` but appears as /<user-name>/<project-name>

But maybe we don't need to proxy it.

**Comment by AbdulrhmnGhanem** [comment]
> * route  `/<user-name>`
>   Proxy to `/search?q=user:user-name` (or however it actually works in Gitea search). Still appears as `/<user-name>`.

What will this display?

**Comment by kasbah** [comment]
The user's projects.
